import { Router, type Response } from 'express';
import { z } from 'zod';
import { availableCredit, availableToPromise, isRouteFeasible, logisticsEstimate } from '../domain/core-data.js';
import { paginate } from '../domain/pagination.js';
import { authenticate, authorize, type AuthenticatedRequest } from '../middleware/auth.js';
import type { CoreDataRepository } from '../repositories/core-data-repository.js';

const pageSchema=z.object({page:z.coerce.number().int().positive().default(1),pageSize:z.coerce.number().int().min(1).max(100).default(25),search:z.string().trim().optional(),status:z.string().optional()});
const productSchema=z.object({code:z.string().trim().min(2).max(30),name:z.string().trim().min(3).max(150),category:z.enum(['PE','PP']),polymerType:z.string().min(2),grade:z.string().min(1),application:z.string().min(2),unitOfMeasure:z.literal('TONNE').default('TONNE'),productionCostPerUnit:z.number().nonnegative(),minimumOrderQuantity:z.number().positive(),shelfLifeDays:z.number().int().positive(),status:z.enum(['ACTIVE','INACTIVE']).default('ACTIVE')});
const feasibilitySchema=z.object({routeId:z.string(),dispatchDate:z.string().date(),requiredDeliveryDate:z.string().date(),quantity:z.number().positive()});
const estimateSchema=z.object({routeId:z.string(),quantity:z.number().positive(),fuelSurchargePercent:z.number().min(0).max(100).default(0)});

function organisation(req:AuthenticatedRequest){return req.user!.organisationId;}
function invalid(res:Response,error:z.ZodError){return res.status(400).json({error:{code:'VALIDATION_ERROR',message:'Request validation failed',issues:error.flatten()}});}

export function coreDataRouter(repository:CoreDataRepository){
  const router=Router(); router.use(authenticate);
  router.get('/products',(req:AuthenticatedRequest,res)=>{const query=pageSchema.safeParse(req.query);if(!query.success)return invalid(res,query.error);let records=repository.products(organisation(req));if(query.data.search){const search=query.data.search.toLowerCase();records=records.filter(x=>`${x.code} ${x.name} ${x.grade}`.toLowerCase().includes(search));}if(query.data.status)records=records.filter(x=>x.status===query.data.status);return res.json(paginate(records,query.data));});
  router.post('/products',authorize('ADMINISTRATOR','COMMERCIAL_PLANNER'),(req:AuthenticatedRequest,res)=>{const parsed=productSchema.safeParse(req.body);if(!parsed.success)return invalid(res,parsed.error);if(repository.products(organisation(req)).some(x=>x.code===parsed.data.code))return res.status(409).json({error:{code:'DUPLICATE_CODE',message:'A product with this code already exists'}});const product=repository.createProduct(organisation(req),parsed.data);repository.createAudit(organisation(req),req.user!.id,'Product',product.id,'CREATE',null,product);return res.status(201).json(product);});
  router.patch('/products/:id',authorize('ADMINISTRATOR','COMMERCIAL_PLANNER'),(req:AuthenticatedRequest,res)=>{const id=String(req.params.id);const parsed=productSchema.partial().safeParse(req.body);if(!parsed.success)return invalid(res,parsed.error);const existing=repository.products(organisation(req)).find(x=>x.id===id);const before=existing?structuredClone(existing):undefined;if(!before)return res.status(404).json({error:{code:'NOT_FOUND',message:'Product not found'}});const product=repository.updateProduct(organisation(req),id,parsed.data)!;repository.createAudit(organisation(req),req.user!.id,'Product',product.id,'UPDATE',before,product);return res.json(product);});
  router.delete('/products/:id',authorize('ADMINISTRATOR'),(req:AuthenticatedRequest,res)=>{const id=String(req.params.id);const before=repository.products(organisation(req)).find(x=>x.id===id);if(!before)return res.status(404).json({error:{code:'NOT_FOUND',message:'Product not found'}});repository.deleteProduct(organisation(req),id);repository.createAudit(organisation(req),req.user!.id,'Product',id,'DELETE',before,null);return res.status(204).send();});
  router.get('/markets',(req:AuthenticatedRequest,res)=>res.json({data:repository.markets(organisation(req))}));
  router.get('/markets/prices',(req:AuthenticatedRequest,res)=>res.json({data:repository.marketPrices(organisation(req))}));
  router.get('/markets/signals',(req:AuthenticatedRequest,res)=>res.json({data:repository.marketSignals(organisation(req))}));
  router.get('/customers',(req:AuthenticatedRequest,res)=>{const query=pageSchema.safeParse(req.query);if(!query.success)return invalid(res,query.error);let records=repository.customers(organisation(req)).map(customer=>({...customer,availableCredit:availableCredit(customer)}));if(query.data.search){const search=query.data.search.toLowerCase();records=records.filter(x=>`${x.code} ${x.name}`.toLowerCase().includes(search));}return res.json(paginate(records,query.data));});
  router.get('/inventory/positions',(req:AuthenticatedRequest,res)=>res.json({data:repository.inventoryPositions(organisation(req)).map(position=>({...position,availableToPromise:availableToPromise(position)}))}));
  router.get('/inventory/summary',(req:AuthenticatedRequest,res)=>{const positions=repository.inventoryPositions(organisation(req));const summary=repository.products(organisation(req)).map(product=>{const matches=positions.filter(x=>x.productId===product.id);return {productId:product.id,productCode:product.code,available:matches.reduce((sum,x)=>sum+x.availableQuantity,0),reserved:matches.reduce((sum,x)=>sum+x.reservedQuantity,0),qualityHold:matches.reduce((sum,x)=>sum+x.qualityHoldQuantity,0),expectedInbound:matches.reduce((sum,x)=>sum+x.expectedInboundQuantity,0),availableToPromise:matches.reduce((sum,x)=>sum+availableToPromise(x),0),ageingQuantity:matches.filter(x=>x.inventoryAgeDays>=120).reduce((sum,x)=>sum+x.availableQuantity,0)};});return res.json({data:summary,totals:{availableToPromise:summary.reduce((sum,x)=>sum+x.availableToPromise,0),ageingQuantity:summary.reduce((sum,x)=>sum+x.ageingQuantity,0)}});});
  router.get('/production/facilities',(req:AuthenticatedRequest,res)=>res.json({data:repository.productionFacilities(organisation(req))}));
  router.get('/production/plans',(req:AuthenticatedRequest,res)=>res.json({data:repository.productionPlans(organisation(req))}));
  router.get('/production/capacity-utilisation',(req:AuthenticatedRequest,res)=>{const plans=repository.productionPlans(organisation(req));const data=repository.productionFacilities(organisation(req)).map(facility=>{const planned=plans.filter(x=>x.facilityId===facility.id).reduce((sum,x)=>sum+x.plannedQuantity,0);return {...facility,plannedQuantity:planned,remainingCapacity:Math.max(0,facility.capacityPerPeriod-planned),utilisationPercent:Number((planned/facility.capacityPerPeriod*100).toFixed(1))};});return res.json({data});});
  router.get('/logistics/routes',(req:AuthenticatedRequest,res)=>res.json({data:repository.logisticsRoutes(organisation(req))}));
  router.post('/logistics/feasibility',(req:AuthenticatedRequest,res)=>{const parsed=feasibilitySchema.safeParse(req.body);if(!parsed.success)return invalid(res,parsed.error);const route=repository.logisticsRoutes(organisation(req)).find(x=>x.id===parsed.data.routeId);if(!route)return res.status(404).json({error:{code:'NOT_FOUND',message:'Route not found'}});return res.json({routeId:route.id,...isRouteFeasible(route,parsed.data.dispatchDate,parsed.data.requiredDeliveryDate,parsed.data.quantity)});});
  router.post('/logistics/cost-estimate',(req:AuthenticatedRequest,res)=>{const parsed=estimateSchema.safeParse(req.body);if(!parsed.success)return invalid(res,parsed.error);const route=repository.logisticsRoutes(organisation(req)).find(x=>x.id===parsed.data.routeId);if(!route)return res.status(404).json({error:{code:'NOT_FOUND',message:'Route not found'}});return res.json({routeId:route.id,currency:'USD',...logisticsEstimate(route,parsed.data.quantity,parsed.data.fuelSurchargePercent)});});
  return router;
}
