import {bootstrapApplication} from '@angular/platform-browser'; import {Component, signal} from '@angular/core'; import {DecimalPipe} from '@angular/common';
@Component({selector:'supplai-root',standalone:true,imports:[DecimalPipe],template:`
<div class="shell"><aside><div class="brand"><b>S</b><span>Suppl<span>AI</span><small>by GIFS</small></span></div><nav><label>DECISION INTELLIGENCE</label><a class="active">▦ Executive overview</a><a>◇ Market opportunities</a><a>◫ Allocation workspace <i>12</i></a><a>⌁ Scenario simulator</a><label>OPERATIONS</label><a>⌁ Demand intelligence</a><a>▤ Inventory & supply</a><a>⚙ Production planning</a><a>⇄ Logistics feasibility</a><label>GOVERNANCE</label><a>✓ Recommendation approvals</a><a>⚙ Business rules</a><a>↥ Data import</a><a>◷ Audit log</a></nav><div class="user">CP <span><b>Commercial Planner</b><small>GIFS Petrochemicals</small></span></div></aside>
<main><header><div><small>GIFS Petrochemicals / Decision intelligence</small><h1>Executive overview</h1></div><div class="controls"><button>Jul – Sep 2026⌄</button><button>◉ Live data</button><button>🔔</button></div></header>
<section class="notice"><span>✦</span><div><b>Decision brief</b><p>Vietnam remains the strongest margin opportunity, while the Malaysian strategic commitment and Indonesia credit exposure require planner attention.</p></div><button>Open allocation workspace →</button></section>
<div class="metrics"><article><small>EXPECTED REVENUE</small><b>$4.83M</b><em>↑ 6.2% vs baseline</em></article><article><small>NET CONTRIBUTION</small><b>$624K</b><em>12.9% margin</em></article><article><small>MARGIN UPLIFT</small><b>+7.4%</b><em>↑ $43K opportunity</em></article><article><small>DEMAND FULFILMENT</small><b>91.6%</b><em>1,140 t unmet</em></article><article><small>ON-TIME FEASIBILITY</small><b>93.1%</b><em>4 route warnings</em></article></div>
<div class="grid"><article class="chart"><div class="title"><span><b>Margin by market</b><small>Expected net contribution</small></span><button>Net margin⌄</button></div><div class="bars">@for(m of markets;track m.name){<div><label>{{m.name}}</label><span><i [style.width.%]="m.value"></i></span><b>{{m.amount}}</b></div>}</div></article><article><div class="title"><span><b>Demand versus supply</b><small>Planning horizon, tonnes</small></span><i class="legend">● Demand　● Supply</i></div><div class="supply"><b>13,570</b><small>Forecast demand</small><hr><b>12,430</b><small>Available-to-promise</small><strong>91.6% covered</strong></div></article></div>
<div class="grid lower"><article><div class="title"><span><b>Top allocation recommendations</b><small>Ranked by risk-adjusted contribution</small></span><button>View all →</button></div>@for(r of recs();track r.market){<div class="rec"><span class="rank">{{r.rank}}</span><div><b>{{r.product}} → {{r.market}}</b><small>{{r.customer}} · {{r.qty}} tonnes</small></div><span><b>{{r.margin}}</b><small>net margin</small></span><label [class.warn]="r.warn">{{r.warn?'Review required':'Feasible'}}</label></div>}</article><article><div class="title"><span><b>Planner attention</b><small>Constraints and risk alerts</small></span></div><div class="alert warning"><b>Credit exposure · Indonesia</b><p>IndoFlex allocation capped at 260 t. $184K revenue at risk.</p></div><div class="alert"><b>Strategic commitment · Malaysia</b><p>400 t minimum volume protected in the baseline plan.</p></div><div class="alert danger"><b>Delivery feasibility · Thailand</b><p>Pasir Gudang route misses the requested date by 3 days.</p></div></article></div>
</main></div>`,styles:[]})
class App{markets=[{name:'Vietnam',value:100,amount:'$182K'},{name:'Malaysia',value:75,amount:'$137K'},{name:'Thailand',value:58,amount:'$106K'},{name:'Indonesia',value:46,amount:'$84K'},{name:'Singapore',value:32,amount:'$59K'}];recs=signal([{rank:1,product:'PP H110MA',market:'Vietnam',customer:'VietPoly Packaging',qty:520,margin:'13.8%',warn:false},{rank:2,product:'PP K8003',market:'Malaysia',customer:'MY Strategic Industries',qty:400,margin:'12.8%',warn:false},{rank:3,product:'HDPE F7000',market:'Indonesia',customer:'IndoFlex Nusantara',qty:260,margin:'9.6%',warn:true}]);}
bootstrapApplication(App).catch(console.error);
